name: Deploy React Frontend to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & build React app
        run: |
          npm install
          npm run build
        working-directory: ./client

      - name: Upload build folder to temporary path
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "client/build/*"
          target: "${{ secrets.SERVER_DEPLOY_PATH }}/build_temp"
          rm: true 

      - name: Replace old build with new one on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ${{ secrets.SERVER_DEPLOY_PATH }}/build
            mv ${{ secrets.SERVER_DEPLOY_PATH }}/build_temp ${{ secrets.SERVER_DEPLOY_PATH }}/build
